// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5MTnESywm9m_SozICCMjQrkN4RBhs_dY',
    appId: '1:537287412583:web:031ff3b991cfe62ba07dc2',
    messagingSenderId: '537287412583',
    projectId: 'image-labelling-c31ba',
    authDomain: 'image-labelling-c31ba.firebaseapp.com',
    storageBucket: 'image-labelling-c31ba.firebasestorage.app',
    measurementId: 'G-0BQEJ1K8LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATf15EVaNhdZ7pn_R3p6IAyRSGCPHeApw',
    appId: '1:537287412583:android:90b483f315744dafa07dc2',
    messagingSenderId: '537287412583',
    projectId: 'image-labelling-c31ba',
    storageBucket: 'image-labelling-c31ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZeFfG2i71ofeZvUqRkqpzV97rxU34JDU',
    appId: '1:537287412583:ios:315a1932082368a2a07dc2',
    messagingSenderId: '537287412583',
    projectId: 'image-labelling-c31ba',
    storageBucket: 'image-labelling-c31ba.firebasestorage.app',
    iosBundleId: 'com.example.mlKitImagelabelCw08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZeFfG2i71ofeZvUqRkqpzV97rxU34JDU',
    appId: '1:537287412583:ios:315a1932082368a2a07dc2',
    messagingSenderId: '537287412583',
    projectId: 'image-labelling-c31ba',
    storageBucket: 'image-labelling-c31ba.firebasestorage.app',
    iosBundleId: 'com.example.mlKitImagelabelCw08',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5MTnESywm9m_SozICCMjQrkN4RBhs_dY',
    appId: '1:537287412583:web:153818631f563732a07dc2',
    messagingSenderId: '537287412583',
    projectId: 'image-labelling-c31ba',
    authDomain: 'image-labelling-c31ba.firebaseapp.com',
    storageBucket: 'image-labelling-c31ba.firebasestorage.app',
    measurementId: 'G-92J2ED48DT',
  );
}
